services:
  devcontainer:
    build:
      context: ..
      dockerfile: Dockerfile
      target: build  # Use the build stage for development
    
    # Override the default command to keep container running for development
    command: sleep infinity
    
    # Mount the source code for live editing
    volumes:
      - ..:/workspace:cached
    
    # Set working directory
    working_dir: /workspace
    
    # Environment variables for development
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - NUGET_XMLDOC_MODE=skip
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
    
    # Enable debugging capabilities
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    
    # Keep stdin open and allocate a pseudo-TTY
    stdin_open: true
    tty: true
